"""Persistence contract for the server-task lifecycle."""

from __future__ import annotations

from collections.abc import Sequence
from typing import Protocol
from uuid import UUID

from app.tasks.models import ServerTask, ServerTaskCreate, TaskOutcome

class ServerTaskStore(Protocol):
    async def initialize(self) -> None: ...
    async def is_healthy(self) -> bool: ...
    async def create(self, conversation_id: UUID, request: ServerTaskCreate) -> ServerTask: ...
    async def get(self, task_id: UUID) -> ServerTask | None: ...
    async def list(self, conversation_id: UUID) -> list[ServerTask]: ...
    async def confirm(self, task_id: UUID) -> ServerTask | None: ...
    async def cancel(self, task_id: UUID) -> ServerTask | None: ...
    async def claim(self, worker_id: str, lease_seconds: int) -> ServerTask | None: ...
    async def update_progress(
        self, task_id: UUID, worker_id: str, *, phase: str, progress: float,
        detail: str, steps: Sequence[str], current_step: int,
    ) -> None: ...
    async def renew(self, task_id: UUID, worker_id: str, lease_seconds: int) -> bool: ...
    async def complete(self, task_id: UUID, worker_id: str, outcome: TaskOutcome) -> None: ...
    async def fail(
        self, task_id: UUID, worker_id: str, message: str, *, retry: bool,
        retry_delay_seconds: int,
    ) -> None: ...
    async def close(self) -> None: ...
