"""Persistence contract for the server-task lifecycle."""

from __future__ import annotations

from collections.abc import Sequence
from typing import Protocol
from uuid import UUID

from app.tasks.models import DeviceToolCall, ServerTask, ServerTaskCreate, TaskOutcome

class ServerTaskStore(Protocol):
    async def initialize(self) -> None: ...
    async def is_healthy(self) -> bool: ...
    async def create(self, conversation_id: UUID, request: ServerTaskCreate) -> ServerTask: ...
    async def get(self, task_id: UUID) -> ServerTask | None: ...
    async def list(self, conversation_id: UUID) -> list[ServerTask]: ...
    async def confirm(self, task_id: UUID) -> ServerTask | None: ...
    async def cancel(self, task_id: UUID) -> ServerTask | None: ...
    async def claim(self, worker_id: str, lease_seconds: int) -> ServerTask | None: ...
    async def update_progress(
        self, task_id: UUID, worker_id: str, *, phase: str, progress: float,
        detail: str, steps: Sequence[str], current_step: int,
    ) -> None: ...
    async def renew(self, task_id: UUID, worker_id: str, lease_seconds: int) -> bool: ...
    async def complete(self, task_id: UUID, worker_id: str, outcome: TaskOutcome) -> None: ...
    async def fail(
        self, task_id: UUID, worker_id: str, message: str, *, retry: bool,
        retry_delay_seconds: int,
    ) -> None: ...
    async def enqueue_device_tool(
        self, task_id: UUID, tool_call_id: str, tool_name: str,
        arguments: dict[str, object],
    ) -> DeviceToolCall: ...
    async def get_pending_device_tool(self, task_id: UUID) -> DeviceToolCall | None: ...
    async def get_device_tool(
        self, task_id: UUID, tool_call_id: str,
    ) -> DeviceToolCall | None: ...
    async def submit_device_tool_result(
        self, task_id: UUID, tool_call_id: str, *,
        result: dict[str, object] | None,
        error_code: str | None,
        error_message: str | None,
    ) -> DeviceToolCall | None: ...
    async def close(self) -> None: ...
